title: Blog Bibliotheks- und Archivinformatik
author: Gins
email: regina.eicher@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  (m)ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik im Herbstsemester 2020 an der FHGR

# social links
github_username:  gins-ctrl # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
